package com.astroremix.horizonsurvey.core

import java.util.Locale

/**
 * Renders a [HorizonProfile] into the file formats Stellarium (and similar
 * planetarium tools) expect: a polygonal "az alt" horizon list plus the
 * landscape.ini that references it, per Stellarium's polygonal landscape
 * spec (polygonal_horizon_list_mode = azDeg_altDeg).
 */
object StellariumHorizonExporter {

    fun buildHorizonTxt(profile: HorizonProfile, surveyLabel: String): String {
        val polygon = profile.sortedClosedPolygon()
        require(polygon.size >= 4) {
            "Need at least 3 distinct-azimuth points to export a horizon, have ${polygon.size - 1}"
        }
        val sb = StringBuilder()
        sb.append("# Horizon survey: $surveyLabel\n")
        sb.append("# Generated by AstroRemix Horizon Surveyor\n")
        sb.append("# azimuth(deg, from north, clockwise)  altitude(deg)\n")
        for (p in polygon) {
            sb.append(formatDegree(p.azimuthDeg))
            sb.append(' ')
            sb.append(formatDegree(p.altitudeDeg))
            sb.append('\n')
        }
        return sb.toString()
    }

    fun buildLandscapeIni(
        landscapeName: String,
        horizonFileName: String,
        author: String? = null,
        description: String? = null,
    ): String {
        val sb = StringBuilder()
        sb.append("[landscape]\n")
        sb.append("name = $landscapeName\n")
        sb.append("type = polygonal\n")
        if (!author.isNullOrBlank()) sb.append("author = $author\n")
        if (!description.isNullOrBlank()) sb.append("description = $description\n")
        sb.append("polygonal_horizon_list = $horizonFileName\n")
        sb.append("polygonal_horizon_list_mode = azDeg_altDeg\n")
        sb.append("polygonal_angle_rotatez = 0.00001\n")
        sb.append("ground_color = .15,.45,.05\n")
        sb.append("horizon_line_color = 0,0,0\n")
        sb.append("minimal_brightness = 0.15\n")
        return sb.toString()
    }

    /** A portable two-column az,alt CSV usable by tools that don't speak Stellarium's format. */
    fun buildAzAltCsv(profile: HorizonProfile): String {
        val sb = StringBuilder("azimuth_deg,altitude_deg\n")
        for (p in profile.sortedClosedPolygon()) {
            sb.append(formatDegree(p.azimuthDeg))
            sb.append(',')
            sb.append(formatDegree(p.altitudeDeg))
            sb.append('\n')
        }
        return sb.toString()
    }

    private fun formatDegree(value: Double): String = String.format(Locale.ROOT, "%.2f", value)
}
